# -*- coding: utf-8 -*-
"""RunUnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA-CxIKtXn9Q-qRdHVQhhCJ9ebzm2wG8
"""

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/start-knitting-girls/UNet/master/

!python resize.py

!python mydata_read.py

!python train.py --data_dir /content/drive/MyDrive/start-knitting-girls/UNet/master/augmented_datasets

!python eval.py

!python display_results.py

"""파일명 재설정"""

import os

# 폴더 경로 설정
inputs_folder = "/content/drive/MyDrive/start-knitting-girls/UNet/master/augmented_datasets/inputs"
labels_folder = "/content/drive/MyDrive/start-knitting-girls/UNet/master/augmented_datasets/labels"

# 파일 목록 가져오기
input_files = set(os.listdir(inputs_folder))
label_files = set(os.listdir(labels_folder))

# 두 폴더에 공통으로 존재하는 파일 필터링
common_files = input_files.intersection(label_files)

# 공통 파일 순회하며 파일 이름 변경
for index, file_name in enumerate(sorted(common_files), start=1):
    # 새 파일 이름 생성
    new_name = f"{index}.jpg"

    # 각 폴더 내 파일 경로
    input_file_path = os.path.join(inputs_folder, file_name)
    label_file_path = os.path.join(labels_folder, file_name)

    # 새 경로 설정
    new_input_file_path = os.path.join(inputs_folder, new_name)
    new_label_file_path = os.path.join(labels_folder, new_name)

    # 파일 이름 변경
    os.rename(input_file_path, new_input_file_path)
    os.rename(label_file_path, new_label_file_path)

    print(f"Renamed {file_name} -> {new_name} in both folders.")